defaults:
  - dataset: kaggle_dogs_vs_cats
  - trainer: default_trainer
  - training: default_training
  - logging: tensorboard
  - optimizer: adamw
  - scheduler: step
  - model: resnet
  - callbacks: callbacks
  - private: custom
  - data: data
  - augmentation: basic_augs

general:
  save_dir: logs/
  workspace: mooziisp
  project_name: kaggle_dogs_vs_cats